<template>
  <div id="app">
    <headerMain />
  </div>
</template>

<script>
import headerMain from "./components/header_main";
export default {
  name: "app",
  components: {
    headerMain,
  },
};
</script>

<style lang="scss">
* {
  width: 100%;
  height: auto;
  overflow-x: hidden;
  box-sizing: border-box;
  padding: 0;
  margin: 0;
  text-decoration: none;
  outline: none;
  cursor: default;
}

/** Generated by FG **/
@font-face {
  font-family: "Conv_Header";
  src: url("./assets/font/Header/fonts/Header.eot");
  src: local("☺"), url("./assets/font/Header/fonts/Header.woff") format("woff"),
    url("./assets/font/Header/fonts/Header.ttf") format("truetype"),
    url("./assets/font/Header/fonts/Header.svg") format("svg");
  font-weight: normal;
  font-style: normal;
}

/** Generated by FG **/
@font-face {
  font-family: "PlayfairDisplay";
  src: url("./assets/font/PlayfairDisplay weigth 700/fonts/PlayfairDisplay-VariableFont_wght.eot");
  src: local("☺"),
    url("./assets/font/PlayfairDisplay weigth 700/fonts/PlayfairDisplay-VariableFont_wght.woff")
      format("woff"),
    url("./assets/font/PlayfairDisplay weigth 700/fonts/PlayfairDisplay-VariableFont_wght.ttf")
      format("truetype"),
    url("./assets/font/PlayfairDisplay weigth 700/fonts/PlayfairDisplay-VariableFont_wght.svg")
      format("svg");
  font-weight: normal;
  font-style: normal;
}

/** Generated by FG **/
@font-face {
  font-family: "Jaffna";
  src: url("./assets/font/PostNoBillsJaffna-SemiBold/fonts/PostNoBillsJaffna-SemiBold.eot");
  src: local("☺"),
    url("./assets/font/PostNoBillsJaffna-SemiBold/fonts/PostNoBillsJaffna-SemiBold.woff")
      format("woff"),
    url("./assets/font/PostNoBillsJaffna-SemiBold/fonts/PostNoBillsJaffna-SemiBold.ttf")
      format("truetype"),
    url("./assets/font/PostNoBillsJaffna-SemiBold/fonts/PostNoBillsJaffna-SemiBold.svg")
      format("svg");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Playfair Display_two";
  src: url("./assets/font/PlayfairDisplay_two/PlayfairDisplay-Black.eot");
  src: local("Playfair Display Italic"), local("PlayfairDisplay-Italic"),
    url("./assets/font/PlayfairDisplay_two/PlayfairDisplay-BlackItalic.eot")
      format("embedded-opentype"),
    url("./assets/font/PlayfairDisplay_two/PlayfairDisplay-BoldItalic.woff2")
      format("woff2"),
    url("./assets/font/PlayfairDisplay_two/PlayfairDisplay-BoldItalic.woff")
      format("woff"),
    url("./assets/font/PlayfairDisplay_two/PlayfairDisplay-Regular.ttf")
      format("truetype");
  font-weight: normal;
  font-style: italic;
}

/** Generated by FG **/
@font-face {
  font-family: "Conv_Raleway-Italic";
  src: url("./assets/font/Raleway-Italic/fonts/Raleway-Italic.eot");
  src: local("☺"),
    url("./assets/font/Raleway-Italic/fonts/Raleway-Italic.woff") format("woff"),
    url("./assets/font/Raleway-Italic/fonts/Raleway-Italic.otf") format("otf"),
    url("./assets/font/Raleway-Italic/fonts/Raleway-Italic.svg") format("svg");
  font-weight: normal;
  font-style: normal;
}
</style>
